### ISSUE TITLE
Mac?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [StreakyCobra/gws#10]
How do I install this on Mac OS X?

**Comment by kniren** [comment]
Just put the bash script that is located on the `src` folder within your path.

**Comment by StreakyCobra** [comment]
Mac is beyond my knowledge. Thanks @kniren for the answer. If anybody is motivated, feel free to send a patch (or PR) to add OS X insructions in the README.

**Comment by kniren** [comment]
It is virtually identical to the *other linux* installation section. Just to clarify a little bit though, I've made a pull request including instructions in the README for setting up the $PATH variable to a directory of your choosing.

**Comment by StreakyCobra** [comment]
Thanks @kniren, merged with credits outside PR: 9090042ea744aa166ae478cac10615610fa8a5d3.
