### ISSUE TITLE
mention the minimum of version number for bash on OSX

### ISSUE THREAD

**Issue by llabball** [StreakyCobra/gws#13]
Thank you for gws - it totally fits my needs. I use it on OSX, Ubuntu and Redhat.

On OSX i had to do an additional installation step: upgrading `bash` like `brew install bash`.

The reason was that the bash version 3 don't includes the `readarray` function. Bash 4 do - so, it is an easy to solve blocker.

**Comment by StreakyCobra** [comment]
With pleasure, glad to hear it is useful.

Comment added!
