### ISSUE TITLE
Repos with common prefix won't work.

### ISSUE THREAD

**Issue by pulkomandy** [StreakyCobra/gws#20]
My layout is:

```
bar
bar-foo
```

gws ignores bar-foo because it has "bar" as a prefix. The function remove_prefixed seems to be the problem, as it doesn't check for / just after the prefix. So it excludes more than subdirectories.

**Comment by StreakyCobra** [comment]
Hi,

Thanks for you contribution!

I was able to reproduce your problem, and indeed the `remove_prefixed` function is the cause. The fix seems simple but I need to check a little bit more if it will cause any other regressions.

BTW the `remove_prefixed` function is used only when calling `gws init` or `gws check`, not when other `gws` commands are called. So in the meantime, just add your `bar-foo` project manually inside the `.projects.gws` and both repository will be used correctly :smiley:
