### ISSUE TITLE
Option to not use color

### ISSUE THREAD

**Issue by ZvikaZ** [StreakyCobra/gws#23]
Hi.
This is an awesome tool! Thanks.

In my setup, the yellow color is unreadable (attaching screenshot)
![gws_color](https://cloud.githubusercontent.com/assets/3908954/13287469/ee65ffb6-db0f-11e5-9715-30c3c2f741dc.JPG)

Although it can be bypassed by piping the output (like `gws | more`), it'd be better if there was some flag, or config option, to disable the colors (or at least the yellow color...)

**Comment by StreakyCobra** [comment]
Hi,

> This is an awesome tool!

Thanks. It probably needs more attention than I can give to it though. I don't have the motivation to fight with `bash` any longer. It's working as it is now (I still use it on every day basis), but there will not be a lot of improvements from my side :pensive: I still hope having time to create a new tool for the exact same purpose, but in a more maintainable language (scoop: I'm starting to learn and love Rust right now)

For your case, I can propose you some solutions (or workaround, depends on the point of view :wink:):

- Define an alias that pass the output to cat to disable the colors (for me colors are an important part of my workflow so I'll probably not do this):

        alias gws="gws|cat"

- Edit (or disable) the [colors](https://github.com/StreakyCobra/gws/blob/3618de83937c895ab38fba75d8cf85b237d343e2/src/gws#L96-L115) directly in the script to adapt them to your need.

- Use a better color scheme in your terminal, here it how mine looks like:

![screenshot](https://i.imgur.com/XLzXBdi.png)

**Comment by ZvikaZ** [comment]
Hi.
Makes sense, I also try to get away from Bash...
Good luck with the rewrite.

Just take into account that if you'll write it in more popular language (maybe Python?) you'd increase the changes of getting code contributions...

I have few more enhacements suggestions.
Are you interested?
(would you prefere that I'll open a new issue for each?)

Thanks again,
Zvika

**Comment by StreakyCobra** [comment]
>  Good luck with the rewrite.

Thanks, but I need to find some free time for this first :pensive: 

> Just take into account that if you'll write it in a more popular language (maybe Python?) you'd increase the chances of getting code contributions...

For sure, but I also want to use Rust in a real application, so… let's see :-)

> I have few more enhacements suggestions.
Are you interested?
(would you prefere that I'll open a new issue for each?)

Yes it's always welcome, it could also be useful for someone else wanting to work on a project like this. Just open a new issue and list all your ideas there :smiley:

**Comment by aveuiller** [comment]
Maybe that's a bit too late, but I just saw this issue, quite randomly.
I had the same problem as @ZvikaZ and made a quick branch on a fork to enable theming of gws, see [here](https://github.com/aveuiller/gws/commit/9e5b7051c52142500c5544e680a0c6a01ad44233).

I can PR you the feature if you are interested.

**Comment by StreakyCobra** [comment]
This change looks nice. If you PR it I'll merge it. Also, as said in the README now, I don't have time to maintain this project anymore. If you have interest in doing so, please let me know :-)

**Comment by emlun** [comment]
This has now been merged into the main development branch, and will be released soon. Thanks for contributing! :)

I also split the color aliases a little more, and added the following:

- `C_ERROR`: red, used in error messages
- `C_VERSION`: red, used in the `gws version` command
- `C_HELP_PROGNAME`: red, used in the usage help texts
- `C_HELP_DIR`: green, used in the usage help texts
