### ISSUE TITLE
Have a flag/loglevel to only show affected repositories

### ISSUE THREAD

**Issue by JohanSpaedtke** [StreakyCobra/gws#29]
This is not a bug but a feature request

I use gws in a situation where i have ~150 repositories. It would be really nice to be able to do

gws ff --someNiceFlag

and have the output only show the repos affected (Dirty (Uncached changes) and/or Clean (fast-forwarded)) but not show all the repos with status Clean at all. 

Regards
//Johan

**Comment by emlun** [comment]
I've thought about this too, by being in literally the same situation... ;)

The current structure of the script isn't very well suited for adding the feature on, but I'll look into it. I don't think it should be that much work.

**Comment by StreakyCobra** [comment]
> The current structure of the script isn't very well suited for adding the feature on

No, and bash doesn't really help 🙈

**Comment by emlun** [comment]
>No, and bash doesn't really help 🙈

Unfortunately, you are very correct. xD

**Comment by JohanSpaedtke** [comment]
Knowing your language preferences you could always take a look here given you want to keep it in bash :P
http://quasimal.com/posts/2012-05-21-funsh.html
https://github.com/mikeplus64/fun.sh

**Comment by emlun** [comment]
I think I got it to work without regressions. @JohanSpaedtke Please try #30 and let me know how it works out!

**Comment by StreakyCobra** [comment]
@JohanSpaedtke Thanks for sharing, I'll bookmark this :smile: 

@emlun Starting this project in bash was fun at beginning, but now I see this at the worst mistake in my life :scream:

**Comment by JohanSpaedtke** [comment]
@emlun seems to work great with `--hide-clean` but maybe update the help text to clarify that 

`gws --hide-clean`

actually works (and I guess is equivalent to `gws status --hide-clean`)

**Comment by JohanSpaedtke** [comment]
One thing though... 
`gws update --hide-clean` 
I would have expected it to only show new repositories but (as stated in the help if you actually read it...) it doesn't do anything at all.

**Comment by emlun** [comment]
Yeah, I've also realized there are a few kinks in the current solution. For one thing, `gws ff` should probably still print those repos that were fast-forwarded.

**Comment by emlun** [comment]
@JohanSpaedtke `update` now also takes the option, please try it out!

**Comment by JohanSpaedtke** [comment]
seems to be working nicely ty :)

**Comment by emlun** [comment]
Nice, then this will be included in the next release. :)
