### ISSUE TITLE
Remove repon not under gws controll or detect rename

### ISSUE THREAD

**Issue by JohanSpaedtke** [StreakyCobra/gws#32]
Yes I know you don't want gws to be destructive but I'll write this issue any way :) 

Imagine the following .projects.gws 

```
team1/repo1 | url1
team1/repo2 | url2
team2/repo3 | url3
```

is changed into the following

```
team1/repo1 | url1
team2/repo2 | url2
team2/repo3 | url3
```

Then it would be nice to run eg.

gws purge

and have it notice that 
```
team1/repo2 | url2
```
no longer exists and therefore remove it.

**Comment by emlun** [comment]
You're right, I won't add a "purge" command. :) But I agree that a way to detect this would be good to have. Fortunately, the `check` command already fulfills this need nicely. ;)

**Comment by JohanSpaedtke** [comment]
Ok next time I'll actually read the documentation first... Check will do 90% of what i want :) Ty very much.
