### ISSUE TITLE
GWS doesn't clone/update missing repositories after 3ea1c54 commit

### ISSUE THREAD

**Issue by Cegree** [StreakyCobra/gws#33]
When you setup your workspace at the first time, it's okay, the repositories are cloned.

If you delete one of them then rerun gws update, contrary to older commits, GWS only says missing repositories without cloning them (even when .cache.gws and .projects.gws are deleted too).

Hope this helps !

Thanks you for this nice script.

@Cegree && @thomas-lemaire

**Comment by emlun** [comment]
Huh, weird. Thanks for the report! It makes no sense that 3ea1c54 would be the culprit, as that commit changed only the README, but I'll look into it.

**Comment by Cegree** [comment]
You're welcome ! It's maybe not this one exactly ... My colleague had its repository pointing to this commit and we tested before and after a git pull, then noticed the bug ...

Good luck !

**Comment by emlun** [comment]
I've identified and fixed the issue, it will be included in the 0.1.12 release!
