### ISSUE TITLE
Typo in line 1111: "gws is an helper..."

### ISSUE THREAD

**Issue by damianfanaro** [StreakyCobra/gws#36]
Change `gws is an helper` for `gws is a helper`.

https://github.com/StreakyCobra/gws/blob/1c3338897f8423056ee6df2823642873ba50fc47/src/gws#L1111

**Comment by emlun** [comment]
Thanks! I went through the source code and README and fixed a few other things too. I don't feel that this is urgent enough for a new release just yet, but the changes are available on master if you want to upgrade for yourself.
