### ISSUE TITLE
`gws --help` says "Not in a workspace"

### ISSUE THREAD

**Issue by yang-ling** [StreakyCobra/gws#37]
When I run `gws --help` , it said "Not in a workspace"

I checked source code,  and found `.projects.gws` file is required by all commands other than `gws init`

I don't think we need `.project.gws` file to run `gws --help`. It only prints help messages after all.

`gws --help` may be the first command a new user would run.  The message "Not in a workspace" would confuse new users like me much.

**Comment by emlun** [comment]
Thanks for the report! I noticed that as well and have already fixed it. :) I'll try to get a release out in the next few days.

**Comment by emlun** [comment]
This is now fixed in [0.1.16](https://github.com/StreakyCobra/gws/releases/tag/0.1.16). Thanks again!
